//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AICanhBaoSucKhoe
    {
        public int CanhBaoID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> NgayCanhBao { get; set; }
        public string LoaiRuiRo { get; set; }
        public string MucDo { get; set; }
        public string NoiDung { get; set; }
        public string HanhDongDeXuat { get; set; }
        public Nullable<bool> DaBoQua { get; set; }
        public Nullable<System.DateTime> NgayBoQua { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
