//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIGoiY
    {
        public int GoiYID { get; set; }
        public string UserID { get; set; }
        public System.DateTime NgayGoiY { get; set; }
        public string NoiDungGoiY { get; set; }
        public Nullable<bool> DaHoanThanh { get; set; }
        public Nullable<System.DateTime> NgayHoanThanh { get; set; }
        public Nullable<int> DiemThuong { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
