//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIPhanTichXuHuong
    {
        public int PhanTichID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> NgayPhanTich { get; set; }
        public string LoaiChiSo { get; set; }
        public string HuongXuHuong { get; set; }
        public Nullable<double> TyLeThayDoi { get; set; }
        public string NhanXet { get; set; }
        public string MucDo { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
