//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiaSeThanhTuu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiaSeThanhTuu()
        {
            this.LuotThichChiaSeThanhTuu = new HashSet<LuotThichChiaSeThanhTuu>();
        }
    
        public int ChiaSeID { get; set; }
        public int ThanhTuuID { get; set; }
        public string NguoiChiaSe { get; set; }
        public Nullable<System.DateTime> NgayChiaSe { get; set; }
        public string DoiTuongXem { get; set; }
        public string ChuThich { get; set; }
        public Nullable<int> SoLuongThich { get; set; }
    
        public virtual ThanhTuu ThanhTuu { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LuotThichChiaSeThanhTuu> LuotThichChiaSeThanhTuu { get; set; }
    }
}
