//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKeHoachTapLuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietKeHoachTapLuyen()
        {
            this.NhatKyHoanThanhBaiTap = new HashSet<NhatKyHoanThanhBaiTap>();
        }
    
        public int ChiTietID { get; set; }
        public string KeHoachID { get; set; }
        public string TenBaiTap { get; set; }
        public Nullable<int> SoHiep { get; set; }
        public Nullable<int> SoLan { get; set; }
        public Nullable<double> CaloTieuHaoDuKien { get; set; }
        public Nullable<int> ThoiGianPhut { get; set; }
        public Nullable<int> NgayTrongTuan { get; set; }
        public Nullable<int> Tuan { get; set; }
        public Nullable<int> ThuTuHienThi { get; set; }
        public Nullable<int> DanhGiaDoKho { get; set; }
        public Nullable<int> DanhGiaHieuQua { get; set; }
        public string VideoUrl { get; set; }
        public string CanhBao { get; set; }
        public string NoiDung { get; set; }
        public string HuongDan { get; set; }
    
        public virtual KeHoachTapLuyen KeHoachTapLuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhatKyHoanThanhBaiTap> NhatKyHoanThanhBaiTap { get; set; }
    }
}
