//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietMauTapLuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietMauTapLuyen()
        {
            this.TheoDoiHoanThanhBaiTap = new HashSet<TheoDoiHoanThanhBaiTap>();
        }
    
        public int BaiTapID { get; set; }
        public int MauTapLuyenID { get; set; }
        public string TenbaiTap { get; set; }
        public Nullable<int> SoSets { get; set; }
        public Nullable<int> SoReps { get; set; }
        public Nullable<int> ThoiLuongPhut { get; set; }
        public Nullable<int> ThoiGianNghiGiay { get; set; }
        public Nullable<int> Tuan { get; set; }
        public Nullable<int> NgayTrongTuan { get; set; }
        public Nullable<int> ThuTuHienThi { get; set; }
        public string VideoUrl { get; set; }
        public string GhiChu { get; set; }
    
        public virtual MauTapLuyen MauTapLuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheoDoiHoanThanhBaiTap> TheoDoiHoanThanhBaiTap { get; set; }
    }
}
