//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKeHoachAnUong
    {
        public int MonAnID { get; set; }
        public int KeHoachAnUongID { get; set; }
        public string BuaAn { get; set; }
        public string TenMonAn { get; set; }
        public string KhauPhan { get; set; }
        public Nullable<int> LuongCalo { get; set; }
        public Nullable<double> Protein { get; set; }
        public Nullable<double> Carbs { get; set; }
        public Nullable<double> ChatBeo { get; set; }
        public Nullable<double> ChatXo { get; set; }
        public Nullable<int> ThuTrongKeHoach { get; set; }
        public Nullable<int> ThuTuHienThi { get; set; }
        public string GhiChuCheBien { get; set; }
        public string LinkCongThuc { get; set; }
    
        public virtual KeHoachAnUong KeHoachAnUong { get; set; }
    }
}
