//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaPT
    {
        public int DanhGiaID { get; set; }
        public string KhachHangID { get; set; }
        public string PTID { get; set; }
        public Nullable<int> Diem { get; set; }
        public string BinhLuan { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
    
        public virtual HuanLuyenVien HuanLuyenVien { get; set; }
        public virtual Users Users { get; set; }
    }
}
