//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatLichPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatLichPT()
        {
            this.GiaoDich = new HashSet<GiaoDich>();
            this.TinNhan = new HashSet<TinNhan>();
        }
    
        public string DatLichID { get; set; }
        public string KhacHangID { get; set; }
        public string PTID { get; set; }
        public System.DateTime NgayGioDat { get; set; }
        public string LoaiBuoiTap { get; set; }
        public string TrangThai { get; set; }
        public string LyDoTuChoi { get; set; }
        public string NguoiHuy { get; set; }
        public Nullable<double> TienHoan { get; set; }
        public Nullable<bool> ChoXemSucKhoe { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual HuanLuyenVien HuanLuyenVien { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDich> GiaoDich { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinNhan> TinNhan { get; set; }
    }
}
