//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DinhDuongMonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DinhDuongMonAn()
        {
            this.NhatKyDinhDuong = new HashSet<NhatKyDinhDuong>();
        }
    
        public string MonAnID { get; set; }
        public string TenMonAn { get; set; }
        public string DonViTinh { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<double> LuongCalo { get; set; }
        public Nullable<double> Protein { get; set; }
        public Nullable<double> ChatBeo { get; set; }
        public Nullable<double> Carbohydrate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhatKyDinhDuong> NhatKyDinhDuong { get; set; }
    }
}
