//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoBaiTapChoUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaoBaiTapChoUser()
        {
            this.TheoDoiHoanThanhBaiTap = new HashSet<TheoDoiHoanThanhBaiTap>();
        }
    
        public int GiaBtID { get; set; }
        public string UserID { get; set; }
        public int MauTapLuyenID { get; set; }
        public string NguoiGiao { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> TuanHienTai { get; set; }
        public Nullable<double> TiLeHoanThanh { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
    
        public virtual MauTapLuyen MauTapLuyen { get; set; }
        public virtual HuanLuyenVien HuanLuyenVien { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheoDoiHoanThanhBaiTap> TheoDoiHoanThanhBaiTap { get; set; }
    }
}
