//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDich
    {
        public string GiaoDichID { get; set; }
        public string DatLichID { get; set; }
        public string KhachHangID { get; set; }
        public string PTID { get; set; }
        public double SoTien { get; set; }
        public Nullable<double> HoaHongApp { get; set; }
        public Nullable<double> SoTienPTNhan { get; set; }
        public string TrangThaiThanhToan { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public Nullable<System.DateTime> NgayGiaoDich { get; set; }
    
        public virtual DatLichPT DatLichPT { get; set; }
        public virtual HuanLuyenVien HuanLuyenVien { get; set; }
        public virtual Users Users { get; set; }
    }
}
