//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoiThanhVien
    {
        public int GoiThanhVienID { get; set; }
        public string UserID { get; set; }
        public string LoaiGoi { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string TrangThai { get; set; }
        public Nullable<double> SoTien { get; set; }
        public string ChuKyThanhToan { get; set; }
        public Nullable<System.DateTime> NgayGiaHan { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public Nullable<bool> TuDongGiaHan { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public Nullable<System.DateTime> NgayHuy { get; set; }
        public string LyDoHuy { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
