//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthTrackerEntities : DbContext
    {
        public HealthTrackerEntities()
            : base("name=HealthTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AICanhBaoSucKhoe> AICanhBaoSucKhoe { get; set; }
        public virtual DbSet<AIGoiY> AIGoiY { get; set; }
        public virtual DbSet<AIPhanTichXuHuong> AIPhanTichXuHuong { get; set; }
        public virtual DbSet<BanBe> BanBe { get; set; }
        public virtual DbSet<Benh> Benh { get; set; }
        public virtual DbSet<ChiaSeThanhTuu> ChiaSeThanhTuu { get; set; }
        public virtual DbSet<ChiTietKeHoachAnUong> ChiTietKeHoachAnUong { get; set; }
        public virtual DbSet<ChiTietKeHoachTapLuyen> ChiTietKeHoachTapLuyen { get; set; }
        public virtual DbSet<ChiTietMauTapLuyen> ChiTietMauTapLuyen { get; set; }
        public virtual DbSet<DanhGiaPT> DanhGiaPT { get; set; }
        public virtual DbSet<DatLichPT> DatLichPT { get; set; }
        public virtual DbSet<DinhDuongMonAn> DinhDuongMonAn { get; set; }
        public virtual DbSet<GoiThanhVien> GoiThanhVien { get; set; }
        public virtual DbSet<GiaoBaiTapChoUser> GiaoBaiTapChoUser { get; set; }
        public virtual DbSet<GiaoDich> GiaoDich { get; set; }
        public virtual DbSet<HuanLuyenVien> HuanLuyenVien { get; set; }
        public virtual DbSet<KeHoachAnUong> KeHoachAnUong { get; set; }
        public virtual DbSet<KeHoachTapLuyen> KeHoachTapLuyen { get; set; }
        public virtual DbSet<LuotThichChiaSeThanhTuu> LuotThichChiaSeThanhTuu { get; set; }
        public virtual DbSet<LuuTruSucKhoe> LuuTruSucKhoe { get; set; }
        public virtual DbSet<MauTapLuyen> MauTapLuyen { get; set; }
        public virtual DbSet<MucTieu> MucTieu { get; set; }
        public virtual DbSet<NhacNho> NhacNho { get; set; }
        public virtual DbSet<NhatKyDinhDuong> NhatKyDinhDuong { get; set; }
        public virtual DbSet<NhatKyDongBo> NhatKyDongBo { get; set; }
        public virtual DbSet<NhatKyHoanThanhBaiTap> NhatKyHoanThanhBaiTap { get; set; }
        public virtual DbSet<NhatKyTamTrang> NhatKyTamTrang { get; set; }
        public virtual DbSet<NhatKyThoiTiet> NhatKyThoiTiet { get; set; }
        public virtual DbSet<NhatKyUngDung> NhatKyUngDung { get; set; }
        public virtual DbSet<PhanCongKeHoachAnUong> PhanCongKeHoachAnUong { get; set; }
        public virtual DbSet<QuyenPT_KhachHang> QuyenPT_KhachHang { get; set; }
        public virtual DbSet<TapTin> TapTin { get; set; }
        public virtual DbSet<TinNhan> TinNhan { get; set; }
        public virtual DbSet<TinhNangGoi> TinhNangGoi { get; set; }
        public virtual DbSet<ThanhTuu> ThanhTuu { get; set; }
        public virtual DbSet<TheoDoiHoanThanhBaiTap> TheoDoiHoanThanhBaiTap { get; set; }
        public virtual DbSet<ThongBao> ThongBao { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<XepHang> XepHang { get; set; }
    }
}
