//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HuanLuyenVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HuanLuyenVien()
        {
            this.DanhGiaPT = new HashSet<DanhGiaPT>();
            this.DatLichPT = new HashSet<DatLichPT>();
            this.GiaoBaiTapChoUser = new HashSet<GiaoBaiTapChoUser>();
            this.GiaoDich = new HashSet<GiaoDich>();
            this.KeHoachAnUong = new HashSet<KeHoachAnUong>();
            this.MauTapLuyen = new HashSet<MauTapLuyen>();
            this.PhanCongKeHoachAnUong = new HashSet<PhanCongKeHoachAnUong>();
            this.QuyenPT_KhachHang = new HashSet<QuyenPT_KhachHang>();
        }
    
        public string PTID { get; set; }
        public string UserID { get; set; }
        public string ChungChi { get; set; }
        public string ChuyenMon { get; set; }
        public Nullable<int> SoNamKinhNghiem { get; set; }
        public string ThanhPho { get; set; }
        public Nullable<double> GiaTheoGio { get; set; }
        public string TieuSu { get; set; }
        public string AnhDaiDien { get; set; }
        public string AnhCCCD { get; set; }
        public string AnhChanDung { get; set; }
        public string FileTaiLieu { get; set; }
        public Nullable<bool> DaXacMinh { get; set; }
        public string GioRanh { get; set; }
        public Nullable<int> SoKhachHienTai { get; set; }
        public Nullable<bool> NhanKhach { get; set; }
        public Nullable<int> TongDanhGia { get; set; }
        public Nullable<double> DiemTrungBinh { get; set; }
        public Nullable<double> TiLeThanhCong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaPT> DanhGiaPT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatLichPT> DatLichPT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoBaiTapChoUser> GiaoBaiTapChoUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDich> GiaoDich { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeHoachAnUong> KeHoachAnUong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MauTapLuyen> MauTapLuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCongKeHoachAnUong> PhanCongKeHoachAnUong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuyenPT_KhachHang> QuyenPT_KhachHang { get; set; }
    }
}
