//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeHoachTapLuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KeHoachTapLuyen()
        {
            this.ChiTietKeHoachTapLuyen = new HashSet<ChiTietKeHoachTapLuyen>();
        }
    
        public string KeHoachID { get; set; }
        public string UserID { get; set; }
        public string MucTieuID { get; set; }
        public string TenKeHoach { get; set; }
        public string LoaiKeHoach { get; set; }
        public string MucDo { get; set; }
        public Nullable<int> SoTuan { get; set; }
        public Nullable<int> SoBuoi { get; set; }
        public Nullable<int> ThoiLuongPhut { get; set; }
        public Nullable<double> CaloTieuHaoMoiBuoi { get; set; }
        public string Nguon { get; set; }
        public Nullable<bool> DangSuDung { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKeHoachTapLuyen> ChiTietKeHoachTapLuyen { get; set; }
        public virtual MucTieu MucTieu { get; set; }
        public virtual Users Users { get; set; }
    }
}
