//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeHoachAnUong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KeHoachAnUong()
        {
            this.ChiTietKeHoachAnUong = new HashSet<ChiTietKeHoachAnUong>();
            this.PhanCongKeHoachAnUong = new HashSet<PhanCongKeHoachAnUong>();
        }
    
        public int KeHoachAnUongID { get; set; }
        public string NguoiTao { get; set; }
        public string TenKeHoach { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> LuongCaloMucTieu { get; set; }
        public string TiLeMacro { get; set; }
        public string LoaiKeHoach { get; set; }
        public Nullable<int> SoNgay { get; set; }
        public string CanhBaoDiUng { get; set; }
        public Nullable<bool> CongKhai { get; set; }
        public Nullable<bool> DaXacThuc { get; set; }
        public Nullable<int> SoLanSuDung { get; set; }
        public Nullable<double> DiemTrungBinh { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKeHoachAnUong> ChiTietKeHoachAnUong { get; set; }
        public virtual HuanLuyenVien HuanLuyenVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCongKeHoachAnUong> PhanCongKeHoachAnUong { get; set; }
    }
}
