//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuotThichChiaSeThanhTuu
    {
        public int ThichID { get; set; }
        public int ChiaSeID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> NgayThich { get; set; }
    
        public virtual ChiaSeThanhTuu ChiaSeThanhTuu { get; set; }
        public virtual Users Users { get; set; }
    }
}
