//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuuTruSucKhoe
    {
        public string MaBanGhi { get; set; }
        public string UserID { get; set; }
        public System.DateTime NgayGhiNhan { get; set; }
        public Nullable<int> SoBuoc { get; set; }
        public Nullable<double> CaloTieuThu { get; set; }
        public Nullable<double> SoGioNgu { get; set; }
        public Nullable<double> CanNang { get; set; }
        public Nullable<double> ChieuCao { get; set; }
        public Nullable<double> BMI { get; set; }
        public Nullable<double> SoDoVong1 { get; set; }
        public Nullable<double> SoDoVong2 { get; set; }
        public Nullable<double> SoDoVong3 { get; set; }
        public Nullable<double> SoDoBapTay { get; set; }
        public Nullable<double> SoDoBapChan { get; set; }
        public Nullable<double> TiLeMo { get; set; }
        public string BenhID { get; set; }
        public Nullable<double> LuongNuocUong { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Benh Benh { get; set; }
        public virtual Users Users { get; set; }
    }
}
