//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MauTapLuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MauTapLuyen()
        {
            this.ChiTietMauTapLuyen = new HashSet<ChiTietMauTapLuyen>();
            this.GiaoBaiTapChoUser = new HashSet<GiaoBaiTapChoUser>();
        }
    
        public int MauTapLuyenID { get; set; }
        public string NguoiTao { get; set; }
        public string TenMauTapLuyen { get; set; }
        public string MoTa { get; set; }
        public string DoKho { get; set; }
        public string MucTieu { get; set; }
        public Nullable<int> SoTuan { get; set; }
        public Nullable<int> CaloUocTinh { get; set; }
        public string ThietBiCan { get; set; }
        public Nullable<bool> CongKhai { get; set; }
        public Nullable<bool> DaXacThuc { get; set; }
        public Nullable<int> SoLanSuDung { get; set; }
        public Nullable<double> DiemTrungBinh { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietMauTapLuyen> ChiTietMauTapLuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoBaiTapChoUser> GiaoBaiTapChoUser { get; set; }
        public virtual HuanLuyenVien HuanLuyenVien { get; set; }
    }
}
