//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MucTieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MucTieu()
        {
            this.KeHoachTapLuyen = new HashSet<KeHoachTapLuyen>();
        }
    
        public string MucTieuID { get; set; }
        public string UserID { get; set; }
        public string LoaiMucTieu { get; set; }
        public double GiaTriMucTieu { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<double> TienDoHienTai { get; set; }
        public Nullable<bool> DaHoanThanh { get; set; }
        public Nullable<int> ThuTuHienThi { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeHoachTapLuyen> KeHoachTapLuyen { get; set; }
        public virtual Users Users { get; set; }
    }
}
