//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhacNho
    {
        public int NhacNhoID { get; set; }
        public string UserID { get; set; }
        public System.DateTime ThoiGianNhac { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> KichHoat { get; set; }
        public string DieuKienThoiTiet { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
