//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKyDinhDuong
    {
        public string DinhDuongID { get; set; }
        public string UserID { get; set; }
        public System.DateTime NgayGhiLog { get; set; }
        public string MonAnID { get; set; }
        public Nullable<double> LuongThucAn { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DinhDuongMonAn DinhDuongMonAn { get; set; }
        public virtual Users Users { get; set; }
    }
}
