//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKyThoiTiet
    {
        public int ThoiTietID { get; set; }
        public string UserID { get; set; }
        public System.DateTime NgayGhiLog { get; set; }
        public string ThanhPho { get; set; }
        public Nullable<double> NhietDo { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<double> DoAm { get; set; }
        public string GoiY { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
