//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKyTamTrang
    {
        public int TamTrangID { get; set; }
        public string UserID { get; set; }
        public System.DateTime NgayGhi { get; set; }
        public string TamTrang { get; set; }
        public Nullable<int> MucDoStress { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
