//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKyDongBo
    {
        public int DongBoID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> NgayDongBo { get; set; }
        public string TrangThaiDongBo { get; set; }
        public string NoiDongBo { get; set; }
        public string ChiTiet { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
