//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKyHoanThanhBaiTap
    {
        public int NhatKyID { get; set; }
        public string UserID { get; set; }
        public int ChiTietID { get; set; }
        public System.DateTime NgayHoanThanh { get; set; }
        public Nullable<int> SoHiepThucTe { get; set; }
        public Nullable<int> SoLanThucTe { get; set; }
        public Nullable<int> ThoiLuongThucTePhut { get; set; }
        public Nullable<double> CaloTieuHao { get; set; }
        public Nullable<int> DanhGiaBaiTap { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ChiTietKeHoachTapLuyen ChiTietKeHoachTapLuyen { get; set; }
        public virtual Users Users { get; set; }
    }
}
