//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKyUngDung
    {
        public int NhatKyID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string MucDoLog { get; set; }
        public string NoiDung { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
