//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCongKeHoachAnUong
    {
        public int PhanCongID { get; set; }
        public string UserID { get; set; }
        public int KeHoachAnUongID { get; set; }
        public string NguoiGiao { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> NgayHienTai { get; set; }
        public Nullable<double> TiLeTuanThu { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
    
        public virtual HuanLuyenVien HuanLuyenVien { get; set; }
        public virtual KeHoachAnUong KeHoachAnUong { get; set; }
        public virtual Users Users { get; set; }
    }
}
