//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TapTin
    {
        public int TapTinID { get; set; }
        public string UserID { get; set; }
        public string TenTapTin { get; set; }
        public string TenLuuTrenServer { get; set; }
        public string DuongDan { get; set; }
        public Nullable<long> KichThuoc { get; set; }
        public string MimeType { get; set; }
        public string LoaiFile { get; set; }
        public string MucDich { get; set; }
        public Nullable<System.DateTime> NgayUpload { get; set; }
        public Nullable<bool> DaXoa { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
