//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhTuu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThanhTuu()
        {
            this.ChiaSeThanhTuu = new HashSet<ChiaSeThanhTuu>();
        }
    
        public int ThanhTuuID { get; set; }
        public string UserID { get; set; }
        public string TenBadge { get; set; }
        public Nullable<int> Diem { get; set; }
        public Nullable<System.DateTime> NgayDatDuoc { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiaSeThanhTuu> ChiaSeThanhTuu { get; set; }
        public virtual Users Users { get; set; }
    }
}
