//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheoDoiHoanThanhBaiTap
    {
        public int TheoDoiID { get; set; }
        public int GiaBtID { get; set; }
        public int BaiTapID { get; set; }
        public System.DateTime NgayHoanThanh { get; set; }
        public Nullable<int> SoSetThucTe { get; set; }
        public Nullable<int> SoRepThucTe { get; set; }
        public Nullable<int> ThoiGianThucTe { get; set; }
        public Nullable<double> CaloTieuHao { get; set; }
        public Nullable<int> DoKho { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ChiTietMauTapLuyen ChiTietMauTapLuyen { get; set; }
        public virtual GiaoBaiTapChoUser GiaoBaiTapChoUser { get; set; }
    }
}
