//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhNangGoi
    {
        public int TinhNangID { get; set; }
        public string TenTinhNang { get; set; }
        public string GoiToiThieu { get; set; }
        public string MoTa { get; set; }
        public Nullable<bool> ConHoatDong { get; set; }
    }
}
