//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinNhan
    {
        public int TinNhanID { get; set; }
        public string NguoiGuiID { get; set; }
        public string NguoiNhanID { get; set; }
        public string DatLichID { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> DaDoc { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
    
        public virtual DatLichPT DatLichPT { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
