//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XepHang
    {
        public int XepHangID { get; set; }
        public string UserID { get; set; }
        public string ChuKy { get; set; }
        public Nullable<int> TongDiem { get; set; }
        public Nullable<int> ThuHang { get; set; }
        public Nullable<System.DateTime> NgayBatDauChuKy { get; set; }
        public Nullable<System.DateTime> NgayKetThucChuKy { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
